SAMPLE_LOGS = [
    {
        "source": "system",
        "host": "srv-01",
        "event_type": "auth",
        "message": "Failed password for invalid user root from 10.0.0.20 port 54321 ssh2",
        "severity": "warning",
        "src_ip": "10.0.0.20",
        "username": "root",
    },
    {
        "source": "system",
        "host": "srv-01",
        "event_type": "auth",
        "message": "Failed password for invalid user root from 10.0.0.20 port 54322 ssh2",
        "severity": "warning",
        "src_ip": "10.0.0.20",
        "username": "root",
    },
    {
        "source": "system",
        "host": "srv-01",
        "event_type": "auth",
        "message": "Failed password for invalid user root from 10.0.0.20 port 54323 ssh2",
        "severity": "warning",
        "src_ip": "10.0.0.20",
        "username": "root",
    },
    {
        "source": "system",
        "host": "srv-01",
        "event_type": "auth",
        "message": "Failed password for invalid user root from 10.0.0.20 port 54324 ssh2",
        "severity": "warning",
        "src_ip": "10.0.0.20",
        "username": "root",
    },
    {
        "source": "system",
        "host": "srv-01",
        "event_type": "auth",
        "message": "Failed password for invalid user root from 10.0.0.20 port 54325 ssh2",
        "severity": "warning",
        "src_ip": "10.0.0.20",
        "username": "root",
    },
    {
        "source": "web",
        "host": "app-01",
        "event_type": "http",
        "message": "GET /admin HTTP/1.1 403 Forbidden",
        "severity": "warning",
        "src_ip": "203.0.113.44",
        "status_code": 403,
        "user_agent": "sqlmap/1.7",
    },
]
